name: Gradle CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: gradle clean build jar

      - name: Show built JAR
        run: ls -l build/libs/

      - name: Upload JAR to AWS EC2 (Amazon Linux)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }} 
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "build/libs/project2-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app/"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t oguzhanyldz/pro2:latest .

      - name: Push Docker image
        run: docker push oguzhanyldz/pro2:latest
